### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by suerion** [SettingDust/MoreProfiling#9]
Hey, here is the Log,

I use Mod Loading Screen and Automodpack, what are using Prelaunch options
https://mclo.gs/efYEz6l
```
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'more-profiling' at 'settingdust.moreprofiling.EntrypointKt::preLaunch'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'more-profiling' at 'settingdust.moreprofiling.EntrypointKt::preLaunch'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 4 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:68)
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.kt:65)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 13 more

```

**Comment by SettingDust** [comment]
It's working fine in my end. You need to find out the minimal reproduce

**Comment by suerion** [comment]
> It's working fine in my end. You need to find out the minimal reproduce

Tried without all mods, there is an problem with your preloading class 
https://mclo.gs/L6Ad3vY

**Comment by SettingDust** [comment]
can't reproduce
But try https://modrinth.com/mod/more-profiling/version/0.14.1. May be fixed

**Comment by suerion** [comment]
Crash with all Mods ->
https://mclo.gs/ew2GtkQ

Crash without Mods, only required
https://mclo.gs/zoXMflu

I use java 21 fabric 0.16.5 with minecraft 1.21.1  with Fabric API 0.105.0
Windows 11
Your new 0.14.1 file

**Comment by suerion** [comment]
https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/net/minecraft/client/MinecraftClient.html

I start an server with this, class_310 is client class? could this be a reason?

**Comment by SettingDust** [comment]
oh yep.

**Comment by SettingDust** [comment]
But it's weird. I never used the class
https://github.com/SettingDust/MoreProfiling/blob/main/src/main/kotlin/settingdust/moreprofiling/Entrypoint.kt#L20-L30

**Comment by SettingDust** [comment]
I found it. Will fix soon

**Comment by SettingDust** [comment]
https://modrinth.com/mod/more-profiling/version/0.14.2

**Comment by suerion** [comment]
Hey, thanks, it worked now fine :)
